version: '3.8'

services:
  postgres-db:
    image: postgres:13
    container_name: desafio-pulse-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: desafio_pulse_db
    ports:
      - "5433:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always